### ISSUE TITLE
Do you think that this is legal?

### ISSUE THREAD

**Issue by yagizhan49** [DrastDev/cPanel-Login-for-MOFH#3]
I doubt this is legal as you're using some (by some, I mean all) code that's owned by cPanel Inc.

**Comment by PCTipsGR** [comment]
I guess it depends on the license that they use, but @DarkW1ND is better suited to answer to this question I think.

**Comment by DarkW1ND** [comment]
Well, I think it can be.

I'll be thinking a little

**Comment by raselmx** [comment]
hey yagizhan .. i need help bro ...
